# station are nodes in the Network graph. Thus, they must remain hashable, so their equality
# functions must not be altered. This is achieved by making the hash function be the station name.
# The station name is set at object initialisation and is read only. The Network object trackls what
# station names have been assigned, and when assigning new station names makes sure they are unique.
#
# The class variables are:
# ._name: the name of the station generated by StationNameGenerator. The Network object tracks names
#         that have been used so that no repeats occur. Therefore, this should be assigned at object
#         initialisation and should not be changed. This is ensured by making name access a property
#         object.
# .lines: a list of the NetworkLine objects that the station is part of
#

import weakref as wr
from NetworkLine import NetworkLine


class NetworkStation:
    def __init__(self, station_name: str):
        self._name = station_name
        self.lines = []

    def __hash__(self):
        return hash(self.name)

    @property
    def name(self) -> str:
        """Returns the station name"""
        return self._name

    def add_line(self, network_line: NetworkLine):
        self.lines.append(wr.ref(network_line))  # using weakref to keep function GC-safe
